services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - dream-team
    environment:
      - POSTGRES_DB=example
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dream-team
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - dream-team
    depends_on:
      - backend

  ml:
    build: ./ml
    ports:
      - "9696:9696"

networks:
  dream-team:
    driver: bridge

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt