services:
  db:
      environment:
        - MONGODB_INITDB_ROOT_USERNAME=$MONGO_ROOT_USER
        - MONGODB_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASS
        - MONGODB_USERNAME=$MONGO_USER
        - MONGODB_PASSWORD=$MONGO_PASS