services:
  db:
      environment:
      - MONGODB_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo-root-user
      - MONGODB_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-pass
      - MONGODB_USERNAME_FILE=/run/secrets/mongo-user
      - MONGODB_PASSWORD_FILE=/run/secrets/mongo-pass
      secrets:
        - mongo-root-user
        - mongo-root-pass
        - mongo-user
        - mongo-pass

secrets:
  mongo-root-pass:
    file: db/mongo_root_pw.txt
  mongo-root-user:
    file: db/mongo_root_uname.txt
  mongo-user:
    file: db/mongo_uname.txt
  mongo-pass:
    file: db/mongo_pw.txt