# ========================= NOTE =========================
# Dependencies for our services atm are the following:
# Frontend  depends on    Backend 
# Backend   depends on    ML,     DB
# ML        depends on    -
# DB        depends on    -


services:
  backend:
    # Backend service for handling requests to ml and db
    build: ./backend
    ports:
      - mode: host
        protocol: tcp
        published: 8080
        target: 8080
    networks:
      - dream-team
    environment:
      - POSTGRES_DB=example
    depends_on:
      ml:
        condition: service_started
      db:
        condition: service_healthy
  db:
    # The database for the backend (and potentially ml)
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dream-team
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    # Frontend service for demo purposes
    build: ./frontend
    ports:
      - mode: host
        protocol: tcp
        published: 3000
        target: 3000
    networks:
      - dream-team
    depends_on:
      - backend

  ml:
    # The machine learning service used for ranking and team forming
    build: ./ml
    ports:
      - mode: host
        protocol: tcp
        published: 9696
        target: 9696

# The network for communication between services
networks:
  dream-team:
    driver: bridge

# The necessary volumes (think persistance)
volumes:
  db-data:

# The necessary secrets
secrets:
  db-password:
    file: db/password.txt