name: DreamTeam CI

on:
  push:
    #branches: [ "staging" ]
  pull_request_target:
    #branches: [ "staging" ]

jobs:
  test_ml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: ./ml
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-full.txt
      
      - name: Run ML tests
        working-directory: ./ml
        run: pytest -v tests/
        #continue-on-error: true

  local_deploy:
    if: github.ref == 'refs/heads/staging' && github.repository_owner == 'TDT4D'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: iterative/setup-dvc@v2
    - name: Fetch data
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        dvc pull -r gd-service
    - name: Build the Docker image
      run: docker compose build
    - name: Deploy the Docker image
      run: docker compose up -d
    - name: Check running containers
      run: docker ps
    - name: Shutdown the Docker image
      run: docker compose down --volumes
    