name: DreamTeam CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

env:
  MONGO_ROOT_USER: ${{ secrets.MONGO_ROOT_USER }}
  MONGO_ROOT_PASS: ${{ secrets.MONGO_ROOT_PASS }}
  MONGO_USER: ${{ secrets.MONGO_USER }}
  MONGO_PASS: ${{ secrets.MONGO_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml -f docker-compose.override.yml build

  local_deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Deploy the Docker image
      run: docker compose f docker-compose.yml -f docker-compose.override.yml up -d
    - name: Check running containers
      run: docker ps
    - name: Shutdown the Docker image
      run: docker compose down
    