name: DreamTeam CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build

  local_deploy:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Fetch DVC data
      env:
       GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        dvc pull
    - name: Deploy the Docker image
      run: docker compose up -d
    - name: Check running containers
      run: docker ps
    - name: Shutdown the Docker image
      run: docker compose down
    